project:
  type: website
  output-dir: docs

website:
  title: "Violaciones a los Derechos Humanos en dictadura"
  favicon: donde_estan.jpg
  site-url: "https://bastianolea.github.io/violaciones_ddhh_chile/"
  open-graph: true
  twitter-card: true
  # announcement: 
  #   icon: info-circle
  #   dismissable: true
  #   content: "**Ayuda:** cualquier idea, aporte o corrección a esta infografía es bienvenido. Por favor [contáctame](https://bastianolea.rbind.io/contact/)!"
  #   type: dark
  #   position: below-navbar
  navbar:
    title: "Infografía"
    background: black
    foreground: "#E7E7E7"
    search: false
    pinned: false
    collapse: false
    tools-collapse: false
    left:
      - text: "Fuentes"
        href: fuentes.qmd
      - text: "Proyecto"
        href: sobre.qmd
      # - text: "Apps"
      #   href: https://bastianolea.github.io/shiny_apps/
      # - text: "Blog"
      #   href: https://bastianolea.rbind.io/blog/
      # - text: "Tutoriales"
      #   href: https://bastianolea.rbind.io/categories/tutoriales/
      # - text: "Yo"
      #   href: https://bastianolea.rbind.io/about/
      # - text: "Contacto"
      #   href: https://bastianolea.rbind.io/contact/
    right:
      - icon: person-fill
        href: https://bastianolea.rbind.io
      - icon: twitter
        href: https://x.com/bastimapache
      - icon: envelope-fill
        href: https://bastianolea.rbind.io/contact/

format:
  html:
    toc: false



