---
title: "Fuentes de información"
format: 
  html:
    theme: [dark, custom.scss]
    grid:
      body-width: 600px
fontfamily: Barlow
lang: es
---

- Informe de la Comisión Nacional sobre Prisión Política y Tortura (Informe Valech).
- Informe de la Comisión Nacional de Verdad y Reconciliación (Informe Rettig).
- Comisión Chilena de Derechos Humanos.
- Amnistía Internacional.
- Comisión de Derechos Humanos de las Naciones Unidas.
- Memoria Viva.
- Asociación de Familiares de Detenidos Desaparecidos, 1995.
- Vicaría de la Solidaridad, 1993.
- Informe de la Comisión ética contra la tortura (CECT) a Ricardo Lagos (2001) y CODEPU.
- Ejecuciones en Chile septiembre-diciembre 1973: El circuito burocrático de la muerte, ArchivosChile, 2012.
- _La misión era matar: el juicio a la caravana Pinochet-Arellano._ Jorge Escalante Hidalgo. Lom Editores. 2000.
- _Historia procesal de Juan Manuel Contreras Sepúlveda en la Corte Suprema,_ Observatorio de Justicia Transicional UDP y Centro de Derechos Humanos UDP, 2015.
- [Erradicación de pobladores de campamentos del área Metropolitana por comuna de origen y destino, 1986](https://www.memoriachilena.gob.cl/602/w3-article-618466.html)
- [Biblioteca del Congreso Nacional de Chile. Periodo 1973-1990, Régimen militar.](https://www.bcn.cl/historiapolitica/hitos_periodo/detalle_periodo.html?per=1973-1990)

#### Prensa
- [_¿Qué pasó con sus hijos?: las diez detenidas embarazadas que la dictadura hizo desaparecer._](https://mmdh.cl/noticias/actualidad-en-dd-hh/post-noticia-150) Museo de la Memoria y los Derechos Humanos
- [Testimonio: trauma, verdad y reparación.](https://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S1607-050X2020000100018#aff1) Elizabeth Lira. Universidad Alberto Hurtado, Santiago, Chile. 2025.
- BBC News, 2023. [La historia de Sebastián Acevedo, el chileno que se quemó a lo bonzo hace 40 años pidiéndole al régimen de Pinochet que le devolviera a sus hijos](https://www.bbc.com/mundo/articles/c808rr5ljx1o.amp)
- BBC Mundo, 2015. [Chile: el testimonio de Carmen Gloria Quintana, la mujer que fue quemada por una patrulla de Pinochet](https://www.bbc.com/mundo/noticias/2013/07/130702_testimonio_carmen_gloria_quintana_aniversario_ch)
- Defensoría de la Niñez: [En memora de niños, niñas y adolescentes víctimas de la violencia de estado durante la dictadura](https://observatorio.defensorianinez.cl/ninezendictadura/)
- [Ciper, 2020. Cómo se ejecutó la orden de Nixon, Kissinger y la CIA: “Efectuar la remoción de Schneider”](https://www.ciperchile.cl/2020/10/22/como-se-ejecuto-la-orden-de-nixon-kissinger-y-la-cia-efectuar-la-remocion-de-schneider/)
- [Le Monde diplomatique, 2015. Las privatizaciones en el Chile 73-90.](https://www.lemondediplomatique.cl/las-privatizaciones-en-el-chile-73-90-por-alicia-gariazzo.html)